/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package racing2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        main_menu classUnderTest = new main_menu();
    }
}
